spring:
  application:
    name: business-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
server:
  port: 8084

logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    io.seata: debug
