spring:
  application:
    name: storage-service
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://118.25.58.79:3306/db_storage?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Yunaxiaozhou&1

  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
server:
  port: 8081
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    io.seata: debug
